apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: auroral-agent
  name: auroral-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: auroral-agent
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: auroral-agent
    spec:
      containers:
        - image: ghcr.io/auroralh2020/auroral-node-agent:latest
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.port }}
          livenessProbe:
            exec:
              command:
                - node
                - healthcheck.js
            failureThreshold: 10
            periodSeconds: 15
            timeoutSeconds: 15
          name: auroral-agent
          resources: {}
          volumeMounts:
            - mountPath: /app/.env
              name: {{ .Release.Name }}-agent-config-volume
              subPath: .env
      restartPolicy: Always
      volumes:
        - name: {{ .Release.Name }}-agent-config-volume
          configMap:
            name: {{ .Release.Name }}-agent-config
status: {}
