apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: auroral-agent
  name: auroral-agent
spec:
  ports:
    - name: {{ .Values.port | quote }}
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
  selector:
    io.kompose.service: auroral-agent
status:
  loadBalancer: {}
