apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gateway
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: gateway
    spec:
      containers:
        - name: gateway
          image: ghcr.io/auroralh2020/auroral_gateway_js:latest
          ports:
            - containerPort: {{ .Values.gtw_port }}
              name: web
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: aur-gateway
              mountPath: /gateway/persistance
            - mountPath: /gateway/.env
              name: {{ .Release.Name }}-gateway-config-volume
              subPath: .env
      initContainers:
        # workaround for avoid mounting empty volumes, see
        # https://stackoverflow.com/a/67091257/5819113
        # https://stackoverflow.com/a/59979968/5819113
        - name: chown-backup-dir-hack
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /data/gateway/persistance"]
          volumeMounts:
            - name: aur-gateway
              mountPath: /data/gateway/persistance
        - name: make-backup-dir
          image: ghcr.io/auroralh2020/auroral_gateway_js:latest
          command: ["cp", "-r", "/gateway/persistance", "/data/gateway/"]
          volumeMounts:
            - name: aur-gateway
              mountPath: /data/gateway/persistance
            - mountPath: /gateway/.env
              name: {{ .Release.Name }}-gateway-config-volume
              subPath: .env
        # - name: launch-gateway-agid-fill
        #   image: ghcr.io/auroralh2020/auroral_gateway_js:latest
        #   command: 
        #     - "/bin/bash"
        #     - "-c"
        #     - |
        #       cd /gateway/persistance/config && ./fillAgid.sh {{ .Values.gtw_id }}
        #   volumeMounts:
        #   - name: aur-gateway
        #     mountPath: /gateway/persistance
        - name: launch-gateway-genkeys
          image: ghcr.io/auroralh2020/auroral_gateway_js:latest
          command: 
            - "/bin/bash"
            - "-c"
            - |
                PUBKEY=/gateway/persistance/keystore/gateway-pubkey.pem
                if test -f "$PUBKEY";
                    then
                    echo "$PUBKEY exists."
                else
                    echo "$PUBKEY does not exist. Generating new ones"
                    cd /gateway/persistance/keystore && ./genkeys.sh;
                fi;
                cat /gateway/persistance/keystore/gateway-pubkey.pem
          volumeMounts:
            - mountPath: /gateway/persistance
              name: aur-gateway
      restartPolicy: Always
      volumes:
        - name: aur-gateway
          persistentVolumeClaim:
            claimName: aur-gateway
        - name: {{ .Release.Name }}-gateway-config-volume
          configMap:
            name: {{ .Release.Name }}-gateway-config
status: {}
