apiVersion: v1
kind: Service
metadata:
  name: helio
  labels:
    io.kompose.service: helio
spec:
  ports:
    - name: {{ .Values.helio_port | quote }}
      port: {{ .Values.helio_port }}
      protocol: TCP
      targetPort: {{ .Values.helio_port }}
  selector:
    io.kompose.service: helio
  type: ClusterIP