apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: proxy
  name: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: proxy
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: proxy
    spec:
      containers:
        - image: ghcr.io/auroralh2020/auroral-node-proxy:latest
          name: proxy
          ports:
            - containerPort: {{ .Values.proxy_port }}
          resources: {}
      restartPolicy: Always
status: {}
