apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: proxy
  name: proxy
spec:
  type: NodePort
  ports:
    - name: {{ .Values.proxy_port | quote }}
      port: {{ .Values.proxy_port }}
      targetPort: {{ .Values.proxy_port }}
  selector:
    io.kompose.service: proxy
status:
  loadBalancer: {}
