apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  DB_PASSWORD: {{ .Values.db_password | b64enc | quote }}
  GTW_ID: {{ .Values.gtw_id | b64enc | quote }}
  GTW_PWD: {{ .Values.gtw_pwd | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-login
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
type: kubernetes.io/dockerconfigjson