version: '2.4'
services:
  helio:
    image: acimmino/helio-rest:latest
    volumes: 
      - type: volume
        source: helio-db
        target: /helio/app
        volume: {}
    ports:
      - '4567:4567'
  frontend:
    image: emiliocrespoperan/helio-frontend:latest
    depends_on:
      - helio
    ports:
      - "4202:80"
    environment:
      - HELIO_REST_HOST=http://localhost:4567
      - HELIO_MODE=APP
volumes:
  helio-db: