version: '2.4'
services:
  helio:
    image: acimmino/helio-rest:latest
    volumes: 
      - type: volume
        source: helio-db
        target: /helio/app
        volume: {}
    ports:
      - '4567:4567'
  frontend:
    image: ghcr.io/auroralh2020/auroral_helio_frontend:latest
    depends_on:
      - helio
    ports:
      - "4201:80"
volumes:
  helio-db: