version: '2.4'
services:
  helio:
    image: acimmino/helio-rest:latest
    volumes: 
      - type: volume
        source: helio-db
        target: /helio/app
        volume: {}
    ports:
      - '4567:4567'
volumes:
  helio-db: