version: '2.4'

services:
  auroral-agent:
    restart: always
    # image: ghcr.io/auroralh2020/auroral-node-agent:beta
    image: ghcr.io/auroralh2020/auroral-node-agent:beta_armv7
    volumes:
    - ./.env:/app/.env:ro
    - ./agent:/app/agent
    depends_on:
      cache-db:
        condition: service_healthy
    extra_hosts:
    - "myhost:host-gateway"
  proxy:
    restart: always
    volumes:
    - ./nginx/logs:/var/log/nginx
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    # - /etc/ssl/bavenir/bavenir_eu.key:/var/certificates/privkey.pem:ro
    # - /etc/ssl/bavenir/bavenir_eu.crt:/var/certificates/fullchain.pem:ro
    depends_on:
      cache-db:
        condition: service_healthy
    ports:
      # - 9997:9997
      - '${EXTERNAL_PORT}:80'
      # - 443:443
    image: nginx:stable
  gateway:
    restart: always
    volumes:
    - ./gateway/log:/gateway/log
    - ./gateway/data:/gateway/data
    - ./gateway/GatewayConfig.xml:/gateway/config/GatewayConfig.xml:ro
    - ./gateway/keystore:/gateway/keystore
    environment:
    - UID=9999
    - GID=9999
    # ports:
    # - 8181:8181
    # image: ghcr.io/auroralh2020/auroral-gateway:beta
    image: ghcr.io/auroralh2020/auroral-gateway:beta_armv7
  cache-db:
    restart: always
    # ports:
    # - 6379:6379
    volumes:
    - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    - ./redis/data:/data
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    command:
    - /usr/local/etc/redis/redis.conf
    image: redis:buster
  # triplestore:
  #   image: acimmino/helio-cloud-rdf4jstore:latest
  #   volumes:
  #    - ./triplestore:/usr/src/helio-cloud-rdf4jstore/rdf4j
  #   ports:
  #     - '4567:4567'
  # wothive:
  #   image: acimmino/wot-hive:latest
  #   volumes:
  #    - ./wothive/configuration.json:/usr/src/wothive/configuration.json
  #   ports:
  #     - '9000:9000'